# Generated by Django 2.0.1 on 2019-05-11 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190511_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='ncdbsampleyearly',
            name='tractpopulation',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
