# Generated by Django 2.0.1 on 2019-05-11 21:58

from django.db import migrations
from api.models import NcdbSampleYearly

def consolidate_years(apps, schema_editor):
    for obj in NcdbSampleYearly.objects.all():

        obj.medinc = obj.medinc_90
        obj.medhomeval = obj.medhomeval_90
        obj.medrentval = obj.medrentval_90
        obj.ownshare = obj.ownshare_90
        obj.whiteshare = obj.whiteshare_90
        obj.blackshare = obj.blackshare_90
        obj.hispshare = obj.hispshare_90
        obj.asothshare = obj.asothshare_90
        obj.rentcbshare = obj.rentcbshare_90
        obj.povrate = obj.povrate_90
        obj.bachshare = obj.bachshare_90
        obj.metmedinc = obj.metmedinc_90
        obj.metmedhomeval = obj.metmedhomeval_90
        obj.metmedrentval = obj.metmedrentval_90
        obj.metownshare = obj.metownshare_90
        obj.metwhiteshare = obj.metwhiteshare_90
        obj.metblackshare = obj.metblackshare_90
        obj.methispshare = obj.methispshare_90
        obj.metasothshare = obj.metasothshare_90
        obj.metrentcbshare = obj.metrentcbshare_90
        obj.metpovrate = obj.metpovrate_90
        obj.metbachshare = obj.metbachshare_90
        obj.year = 1990
        obj.save()

        obj.index = None
        obj.medinc = obj.medinc_00
        obj.medhomeval = obj.medhomeval_00
        obj.medrentval = obj.medrentval_00
        obj.ownshare = obj.ownshare_00
        obj.whiteshare = obj.whiteshare_00
        obj.blackshare = obj.blackshare_00
        obj.hispshare = obj.hispshare_00
        obj.asothshare = obj.asothshare_00
        obj.rentcbshare = obj.rentcbshare_00
        obj.povrate = obj.povrate_00
        obj.bachshare = obj.bachshare_00
        obj.metmedinc = obj.metmedinc_00
        obj.metmedhomeval = obj.metmedhomeval_00
        obj.metmedrentval = obj.metmedrentval_00
        obj.metownshare = obj.metownshare_00
        obj.metwhiteshare = obj.metwhiteshare_00
        obj.metblackshare = obj.metblackshare_00
        obj.methispshare = obj.methispshare_00
        obj.metasothshare = obj.metasothshare_00
        obj.metrentcbshare = obj.metrentcbshare_00
        obj.metpovrate = obj.metpovrate_00
        obj.metbachshare = obj.metbachshare_00
        obj.year = 2000
        obj.save()

        obj.index = None
        obj.medinc = obj.medinc_10
        obj.medhomeval = obj.medhomeval_10
        obj.medrentval = obj.medrentval_10
        obj.ownshare = obj.ownshare_10
        obj.whiteshare = obj.whiteshare_10
        obj.blackshare = obj.blackshare_10
        obj.hispshare = obj.hispshare_10
        obj.asothshare = obj.asothshare_10
        obj.rentcbshare = obj.rentcbshare_10
        obj.povrate = obj.povrate_10
        obj.bachshare = obj.bachshare_10
        obj.metmedinc = obj.metmedinc_10
        obj.metmedhomeval = obj.metmedhomeval_10
        obj.metmedrentval = obj.metmedrentval_10
        obj.metownshare = obj.metownshare_10
        obj.metwhiteshare = obj.metwhiteshare_10
        obj.metblackshare = obj.metblackshare_10
        obj.methispshare = obj.methispshare_10
        obj.metasothshare = obj.metasothshare_10
        obj.metrentcbshare = obj.metrentcbshare_10
        obj.metpovrate = obj.metpovrate_10
        obj.metbachshare = obj.metbachshare_10
        obj.tractpopulation = obj.tractpopulation2010
        obj.year = 2010
        obj.save()

        obj.index = None
        obj.medinc = obj.medinc_17
        obj.medhomeval = obj.medhomeval_17
        obj.medrentval = obj.medrentval_17
        obj.ownshare = obj.ownshare_17
        obj.whiteshare = obj.whiteshare_17
        obj.blackshare = obj.blackshare_17
        obj.hispshare = obj.hispshare_17
        obj.asothshare = obj.asothshare_17
        obj.rentcbshare = obj.rentcbshare_17
        obj.povrate = obj.povrate_17
        obj.bachshare = obj.bachshare_17
        obj.metmedinc = obj.metmedinc_17
        obj.metmedhomeval = obj.metmedhomeval_17
        obj.metmedrentval = obj.metmedrentval_17
        obj.metownshare = obj.metownshare_17
        obj.metwhiteshare = obj.metwhiteshare_17
        obj.metblackshare = obj.metblackshare_17
        obj.methispshare = obj.methispshare_17
        obj.metasothshare = obj.metasothshare_17
        obj.metrentcbshare = obj.metrentcbshare_17
        obj.metpovrate = obj.metpovrate_17
        obj.metbachshare = obj.metbachshare_17
        obj.year = 2017
        obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_ncdbsampleyearly_tractpopulation'),
    ]

    operations = [
        migrations.RunPython(consolidate_years)
    ]
