# Generated by Django 2.0.1 on 2019-05-11 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190511_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='ncdbsamplechanges',
            name='chasothshare',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ncdbsamplechanges',
            name='chbachshare',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ncdbsamplechanges',
            name='chblackshare',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ncdbsamplechanges',
            name='chhispshare',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ncdbsamplechanges',
            name='chhomeval',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ncdbsamplechanges',
            name='chinc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ncdbsamplechanges',
            name='chownshare',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ncdbsamplechanges',
            name='chpovrate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ncdbsamplechanges',
            name='chrent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ncdbsamplechanges',
            name='chrentcbshare',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ncdbsamplechanges',
            name='chwhiteshare',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ncdbsamplechanges',
            name='metchasothshare',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ncdbsamplechanges',
            name='metchbachshare',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ncdbsamplechanges',
            name='metchblackshare',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ncdbsamplechanges',
            name='metchhispshare',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ncdbsamplechanges',
            name='metchhomeval',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ncdbsamplechanges',
            name='metchownshare',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ncdbsamplechanges',
            name='metchpovrate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ncdbsamplechanges',
            name='metchrent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ncdbsamplechanges',
            name='metchrentcbshare',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ncdbsamplechanges',
            name='metchwhiteshare',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
