# Generated by Django 2.0.1 on 2019-05-11 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190511_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='ncdbsamplechanges',
            name='end_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ncdbsamplechanges',
            name='start_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
