# Generated by Django 2.0.1 on 2019-05-11 23:58

from django.db import migrations
from api.models import NcdbSampleChanges

def consolidate_change_years(apps, schema_editor):
    for obj in NcdbSampleChanges.objects.all():

        # 1990 - 2017
        obj.chrent = obj.chrent_9017
        obj.chinc = obj.chinc_9017
        obj.chhomeval = obj.chhomeval_9017
        obj.chbachshare = obj.chbachshare_9017
        obj.chwhiteshare = obj.chwhiteshare_9017
        obj.chblackshare = obj.chblackshare_9017
        obj.chhispshare = obj.chhispshare_9017
        obj.chasothshare = obj.chasothshare_9017
        obj.chownshare = obj.chownshare_9017
        obj.chpovrate = obj.chpovrate_9017
        obj.chrentcbshare = obj.chrentcbshare_9017
        obj.metchbachshare = obj.metchbachshare_9017
        obj.metchrent = obj.metchrent_9017
        obj.metchhomeval = obj.metchhomeval_9017
        obj.metchpovrate = obj.metchpovrate_9017
        obj.metchownshare = obj.metchownshare_9017
        obj.metchrentcbshare = obj.metchrentcbshare_9017
        obj.metchwhiteshare = obj.metchwhiteshare_9017
        obj.metchblackshare = obj.metchblackshare_9017
        obj.metchhispshare = obj.metchhispshare_9017
        obj.metchasothshare = obj.metchasothshare_9017
        obj.start_year = 1990
        obj.end_year = 2017
        obj.save()

        # 1990 - 2016
        obj.index = None
        obj.metchrent = obj.metchrent_9016
        obj.metchhomeval = obj.metchhomeval_9016
        obj.start_year = 1990
        obj.end_year = 2016
        obj.save()

        # 1990 - 2000
        obj.index = None
        obj.metchbachshare = obj.metchbachshare_9000
        obj.metchrent = obj.metchrent_9000
        obj.metchhomeval = obj.metchhomeval_9000
        obj.metchpovrate = obj.metchpovrate_9000
        obj.metchownshare = obj.metchownshare_9000
        obj.metchrentcbshare = obj.metchrentcbshare_9000
        obj.metchwhiteshare = obj.metchwhiteshare_9000
        obj.metchblackshare = obj.metchblackshare_9000
        obj.metchhispshare = obj.metchhispshare_9000
        obj.metchasothshare = obj.metchasothshare_9000
        obj.start_year = 1990
        obj.end_year = 2000
        obj.save()

        # 2000 - 2017
        obj.index = None
        obj.chrent = obj.chrent_0017
        obj.chinc = obj.chinc_0017
        obj.chhomeval = obj.chhomeval_0017
        obj.chbachshare = obj.chbachshare_0017
        obj.chwhiteshare = obj.chwhiteshare_0017
        obj.chblackshare = obj.chblackshare_0017
        obj.chhispshare = obj.chhispshare_0017
        obj.chasothshare = obj.chasothshare_0017
        obj.chownshare = obj.chownshare_0017
        obj.chpovrate = obj.chpovrate_0017
        obj.chrentcbshare = obj.chrentcbshare_0017
        obj.metchbachshare = obj.metchbachshare_0017
        obj.metchrent = obj.metchrent_0017
        obj.metchhomeval = obj.metchhomeval_0017
        obj.metchpovrate = obj.metchpovrate_0017
        obj.metchownshare = obj.metchownshare_0017
        obj.metchrentcbshare = obj.metchrentcbshare_0017
        obj.metchwhiteshare = obj.metchwhiteshare_0017
        obj.metchblackshare = obj.metchblackshare_0017
        obj.metchhispshare = obj.metchhispshare_0017
        obj.metchasothshare = obj.metchasothshare_0017
        obj.start_year = 2000
        obj.end_year = 2017
        obj.save()

        # 2000 - 2010
        obj.index = None
        obj.metchbachshare = obj.metchbachshare_0010
        obj.metchrent = obj.metchrent_0010
        obj.metchhomeval = obj.metchhomeval_0010
        obj.metchpovrate = obj.metchpovrate_0010
        obj.metchownshare = obj.metchownshare_0010
        obj.metchrentcbshare = obj.metchrentcbshare_0010
        obj.metchwhiteshare = obj.metchwhiteshare_0010
        obj.metchblackshare = obj.metchblackshare_0010
        obj.metchhispshare = obj.metchhispshare_0010
        obj.metchasothshare = obj.metchasothshare_0010
        obj.start_year = 2000
        obj.end_year = 2010
        obj.save()

        # 2010 - 2017
        obj.index = None
        obj.chrent = obj.chrent_1017
        obj.chinc = obj.chinc_1017
        obj.chhomeval = obj.chhomeval_1017
        obj.chbachshare = obj.chbachshare_1017
        obj.chwhiteshare = obj.chwhiteshare_1017
        obj.chblackshare = obj.chblackshare_1017
        obj.chhispshare = obj.chhispshare_1017
        obj.chasothshare = obj.chasothshare_1017
        obj.chownshare = obj.chownshare_1017
        obj.chpovrate = obj.chpovrate_1017
        obj.chrentcbshare = obj.chrentcbshare_1017
        obj.metchbachshare = obj.metchbachshare_1017
        obj.metchrent = obj.metchrent_1017
        obj.metchhomeval = obj.metchhomeval_1017
        obj.metchpovrate = obj.metchpovrate_1017
        obj.metchownshare = obj.metchownshare_1017
        obj.metchrentcbshare = obj.metchrentcbshare_1017
        obj.metchwhiteshare = obj.metchwhiteshare_1017
        obj.metchblackshare = obj.metchblackshare_1017
        obj.metchhispshare = obj.metchhispshare_1017
        obj.metchasothshare = obj.metchasothshare_1017
        obj.start_year = 2000
        obj.end_year = 2017
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20190511_2357'),
    ]

    operations = [
        migrations.RunPython(consolidate_change_years)
    ]
